### ISSUE TITLE
Error Building DRAM Driver in Cross-Compilation with Docker

### ISSUE THREAD

**Issue by naortega** [AdrianKoshka/macc-uefi-build-script#5]
While trying to cross-compile the flash image in a docker container, I came across the following error:
```
Building DRAM driver
  CC      mv_ddr4_training_leveling.c
In file included from ddr3_init.h:116,
                 from mv_ddr4_training_leveling.c:100:
mv_ddr4_training_leveling.c: In function ‘mv_ddr4_xsb_comp_test’:
mv_ddr4_training_leveling.c:252:38: error: format ‘%llx’ expects argument of type ‘long long unsigned int’, but argument 2 has type ‘uint64_t’ {aka ‘long unsigned int’} [-Werror=format=]
  252 |    DEBUG_LEVELING(DEBUG_LEVEL_INFO, ("0x%16llx\n", read_pattern_64[edge]));
      |                                      ^~~~~~~~~~~~  ~~~~~~~~~~~~~~~~~~~~~
      |                                                                   |
      |                                                                   uint64_t {aka long unsigned int}
ddr3_logging_def.h:155:10: note: in definition of macro ‘DEBUG_LEVELING’
  155 |   printf s
      |          ^
mv_ddr4_training_leveling.c:252:46: note: format string is defined here
  252 |    DEBUG_LEVELING(DEBUG_LEVEL_INFO, ("0x%16llx\n", read_pattern_64[edge]));
      |                                         ~~~~~^
      |                                              |
      |                                              long long unsigned int
      |                                         %16lx
cc1: all warnings being treated as errors
make[1]: *** [Makefile:470: /opt/e2b/trusted-firmware-a/build/a80x0_mcbin/release/ble/mv_ddr4_training_leveling.o] Error 1
make: *** [plat/marvell/armada/a8k/common/ble/ble.mk:35: /opt/e2b/trusted-firmware-a/build/a80x0_mcbin/release/ble/mv_ddr_lib.a] Error 2
make: Leaving directory '/opt/e2b/trusted-firmware-a'
cp: cannot stat 'trusted-firmware-a/build/a80x0_mcbin/release/flash-image.bin': No such file or directory
```

It would seem to be an upstream error, though I'm unsure as to why such a conversion (less precise to more precise) would be the cause of such an error.

As a side note, I would like to ask if any working image is available for download to burn to an SD card.

**Comment by naortega** [comment]
I tried with podman, and I get the same issue.

**Comment by AdrianKoshka** [comment]
> As a side note, I would like to ask if any working image is available for download to burn to an SD card.

Don't believe I have any, sorry. Though Solid Run does provide them https://images.solid-run.com/8040/UEFI

**Comment by naortega** [comment]
> Don't believe I have any, sorry. Though Solid Run does provide them https://images.solid-run.com/8040/UEFI

I've seen that, although it would seem that image only works for the SPI.

**Comment by AdrianKoshka** [comment]
I'm fairly sure they work on microSD card as well, I remember using them for that way back when I got my macchiatobin singleshot.

**Comment by naortega** [comment]
[mcbin-error.txt](https://github.com/AdrianKoshka/macc-uefi-build-script/files/7686586/mcbin-error.txt)

I've tried doing that, but I get this extremely verbose error. It's the same one I get if I try booting the same image from the SPI. Not sure what the issue is referring to.

**Comment by AdrianKoshka** [comment]
This starts going beyond my knowledge, perhaps you'll have more luck in the #solidrun channel of this discord server I'm in: https://discord.gg/xFpM3XFS

**Comment by naortega** [comment]
I'm actually in that discord server, but I haven't been given any useful information.

**Comment by naortega** [comment]
Although I likely derailed the main objective of this issue with asking for a flash image, it continues to be an issue that the build (at least on my machine) gives this error.

**Comment by AdrianKoshka** [comment]
I believe you'll have more luck asking the folks who develop/maintain TF-A why it isn't building than you'll have with me.

**Comment by AdrianKoshka** [comment]
So I was barking up the wrong tree and obviously not reading the compiler error output. PR #6 should resolve the issue you were having.
